version: "3.7"

services:
    web:
        build: ./web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./web/:/web/
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
    db:
        image: postgres:12.0-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    redis:
        image: "redis:alpine"
        restart: always
        ports:
            - 6379:6379
    worker:
        build: ./web
        restart: always
        command: celery -A <project_name> worker --loglevel=info
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
    beat:
        build: ./web
        restart: always
        command: celery -A <project_name> beat --loglevel=info
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
volumes:
    postgres_data:
    web:
